//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sushi.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero.
        /// </summary>
        public static string gridFirst {
            get {
                return ResourceManager.GetString("gridFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ids from _START_ to _END_ of _TOTAL_ total.
        /// </summary>
        public static string gridInfo {
            get {
                return ResourceManager.GetString("gridInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ids from 0 to 0 of 0 total.
        /// </summary>
        public static string gridInfoEmpty {
            get {
                return ResourceManager.GetString("gridInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total).
        /// </summary>
        public static string gridInfoFiltered {
            get {
                return ResourceManager.GetString("gridInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string gridInfoPostFix {
            get {
                return ResourceManager.GetString("gridInfoPostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo.
        /// </summary>
        public static string gridLast {
            get {
                return ResourceManager.GetString("gridLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display &lt;select&gt;&lt;option value=&apos;10&apos;&gt;10&lt;/option&gt;&lt;option value=&apos;20&apos;&gt;20&lt;/option&gt;&lt;option value=&apos;50&apos;&gt;50&lt;/option&gt;&lt;option value=&apos;100&apos;&gt;100&lt;/option&gt;&lt;option value=&apos;-1&apos;&gt;all&lt;/option&gt;&lt;/select&gt; ids.
        /// </summary>
        public static string gridLengthMenu {
            get {
                return ResourceManager.GetString("gridLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string gridNext {
            get {
                return ResourceManager.GetString("gridNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string gridPrevious {
            get {
                return ResourceManager.GetString("gridPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait please.
        /// </summary>
        public static string gridProcessing {
            get {
                return ResourceManager.GetString("gridProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string gridSearch {
            get {
                return ResourceManager.GetString("gridSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string gridUrl {
            get {
                return ResourceManager.GetString("gridUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ids found..
        /// </summary>
        public static string gridZeroRecords {
            get {
                return ResourceManager.GetString("gridZeroRecords", resourceCulture);
            }
        }
    }
}
